sonar.host.url=https://sonarcloud.io
sonar.organization=dmancilla85
sonar.projectKey=dmancilla85_java-mvn-laslo
sonar.projectName=LoopMatcher (LASLO)
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.resources=src/main/resources
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8
