/*
 * Copyright (C) 2018 david
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.eljaguar.mvnlaslo.gui;

import javax.swing.*;
import java.awt.*;

/**
 * @author david
 */
public class AboutFrame extends javax.swing.JFrame {

    /**
     * Creates new form AboutFrame
     */
    public AboutFrame() {


        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel jPanel1 = new JPanel();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JButton jButton1 = new JButton();
        JScrollPane jScrollPane1 = new JScrollPane();
        JTextArea jTxtInfo = new JTextArea();

        setTitle("About FInd-A-Loop...");
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(480, 600));
        setPreferredSize(new java.awt.Dimension(480, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(480, 300));
        setType(java.awt.Window.Type.POPUP);

        jButton1.setText("Exit");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jTxtInfo.setEditable(false);
        jTxtInfo.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        jTxtInfo.setColumns(20);
        jTxtInfo.setFont(new java.awt.Font("Calibri Light", Font.PLAIN, 14)); // NOI18N
        jTxtInfo.setLineWrap(true);
        jTxtInfo.setRows(5);
        jTxtInfo.setTabSize(4);
        jTxtInfo.setText("Designed to find stem-loops structures with defined loop patterns. Supports FASTA and GenBank file format. \nPredicts the secondary structure with RNAFold. \nUses the U-Shuffle algorithm to generate shuffled sequences.\nAble to download GenBank sequences online from NCBI.\n\nDesigned in colaboration with RNA Celular Biology Lab at Leloir Institute. \nDeveloped by: David A. Mancilla\ne-mail: david.a.m@live.com\n\nCopyright (C) 2018"); // NOI18N
        jTxtInfo.setWrapStyleWord(true);
        jTxtInfo.setAutoscrolls(false);
        jTxtInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(jTxtInfo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(193, 193, 193)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addContainerGap(234, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    // End of variables declaration//GEN-END:variables

}
